
[package]
name = "kelp"
version = "0.0.1"
authors = ["Jáchym Tomášek"]
edition = "2018"

[dependencies]
agar = "*"
pest = "2.1"
pest_derive = "2.1"
#daggy = "0.7"
uuid = {version = "0.8", features = ["v4"]}
colored = "2"
#lalrpop-util = "0.19.0"
regex = "1"
lazy_static = "1.4"