[package]
name = "kelp"
version = "0.0.1"
authors = ["Jáchym Tomášek"]
edition = "2018"
categories = ["compilers"]
license = "Apachev2"
readme = "README.md"

[workspace]
members = ["crates/*"]

[dependencies]
kelp_app = {path = "crates/kelp_app", version = "*"}
