[package]
name = "kelp_message"
version = "0.0.1"
authors = ["Jáchym Tomášek"]
edition = "2018"

[dependencies]
kelp_span = {path = "../kelp_span", version = "*"}

colored = "2"
regex = "1"
lazy_static = "1.4"
pest = "2.1"
